routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontendController@index')->name('frontend.index');
Route::get('{SlugOrId}/detail', 'FrontendController@detail')->name('frontend.detail');
Route::get('{SlugOrId}/{medium}/{campaign}/{reference}/url-encode/', 'UrlmodifierController@encode')->name('encode-url');
Route::get('{HashCode}/url-decode/', 'UrlmodifierController@decode')->name('decode-url');
Auth::routes();
Route::middleware(['auth'])->group(function () {
	Route::get('/home', 'HomeController@index')->name('home');
	Route::resource('entries', 'EntryController');

	Route::resource('trackings', 'TrackingController')->only([
	    'index', 'show'
	]);
});

app/Http/Controllers/FrontendController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Entry as Blog;
use Flash;

class FrontendController extends Controller
{

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $entries = Blog::orderBy('entry_date', 'desc')->paginate(env('PAGINATION_HOME'));
        return view('frontend.index')
            ->with('entries', $entries);
    }



    /**
     * Display the specified Entry.
     *
     * @param int $id
     *
     * @return Response
     */
    public function detail($idOrSlug)
    {
        /** @var Entry $entry */
        $entry = Blog::where('slug',$idOrSlug)->orWhere('id',$idOrSlug)->first();
        
        if (empty($entry)) {

            Flash::error('Blog not found');

            return redirect(route('frontend.index'));
        }

        return view('frontend.show')->with('entry', $entry);
    }
}

resources/views/frontend/action.blade.php
@php

@endphp
<div class="form-group col-sm-12">
    <a target="_blank" href="{{ route('encode-url', [$entry->slug, 'email', 'email-cam-aug-20', base64_encode(URL::current())]) }}" class='btn btn-info'>Email</a>
    <a target="_blank" href="{{ route('encode-url', [$entry->slug, 'whatsapp', 'whatsapp-cam-aug-20', base64_encode(URL::current())]) }}" class='btn btn-info'>WhatsApp</a>
    <a target="_blank" href="{{ route('encode-url', [$entry->slug, 'facebook', 'fb-cam-aug-20', base64_encode(URL::current())]) }}" class='btn btn-info'>Facebook</a>
    <a target="_blank" href="{{ route('encode-url', [$entry->slug, 'instagram', 'instagram-cam-aug-20', base64_encode(URL::current())]) }}" class='btn btn-info'>Instagram</a>
    <a target="_blank" href="{{ route('encode-url', [$entry->slug, 'linkedin', 'linkedin-cam-aug-20', base64_encode(URL::current())]) }}" class='btn btn-info'>Linkedin</a>
</div>

resources/views/frontend/grid.blade.php
<div class="row">
        @foreach($entries as $entry)

            <div class="form-group col-2 {{$entry->deleted_at!=null?'deleted':''}}">
                <div class="card">
                  <div class="card-body">
                    <div class="card-text">
                        <div class="clearfix">
                            <label>Date :</label> 
                            <span>{{$entry->entry_date->format('Y-m-d')}}</span>
                        </div>
                        <div class="clearfix">
                            <span>{{substr($entry->title,0,50)}}{{(strlen($entry->title)>50)?'...':''}}</span>
                        </div>
                        <div class="clearfix {{$entry->deleted_at!=null?'span-deleted':''}}">
                            
                                <a href="{{ route('frontend.detail', [$entry->slug ]) }}" class='btn btn-primary'>View</a>
        
                                @include('frontend.action')
                               
                            </span>
                        </div>                                  
                    </div>
                  </div>
                </div>  
            </div>  
        @endforeach
</div>

@section('css')
<style>
.deleted .card{
    background-color: #80808030;
    -webkit-text-decoration-line: line-through;
    text-decoration-line: line-through;
}
.deleted .span-deleted{
    text-decoration: none;
    display: inline-block;
}
.card-body{
    min-height: 201px;
}
</style>
@endsection

resources/views/frontend/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">



    @include('frontend.grid')
</div>
@endsection

resources/views/frontend/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    @include('frontend.show_fields')

  
    <div class="clearfix">
    	<a href="{{ route('frontend.index') }}" class="btn btn-info">Back</a>
    </div>

    <div class="clearfix"><br /></div>
    
    <div class="clearfix">
        

            @include('frontend.action')
           
    </div> 
</div>
@endsection

resources/views/frontend/show_fields.blade.php
<!-- Entry Date Field -->
<div class="form-group col-sm-6">
    {!! Form::label('entry_date', 'Entry Date:') !!}
    <p>{{ $entry->entry_date->format('Y-m-d') }}</p>
</div>

<!-- Entry Title Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('title', 'Entry Title:') !!}
    <p>{{ $entry->title }}</p>
</div>



<!-- Entry Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('entry', 'Entry:') !!}
    <p>{{ $entry->entry }}</p>
</div>

resources/views/frontend/table.blade.php
<div class="table-responsive">
    <table class="table" id="entries-table">
        <thead>
            <tr>
                <th>#ID</th>
        <th>Entry</th>
        <th>Entry Date</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($entries as $entry)
            <tr class="{{$entry->deleted_at!=null?'deleted':''}}">
                <td>{{ $entry->id }}</td>
            <td>{{substr($entry->title,0,25)}}{{(strlen($entry->title)>25)?'...':''}}</td>
            <td>{{ $entry->entry_date->format('Y-m-d') }}</td>
                <td>
                    {{--
                    @if($entry->deleted_at)
                    <p>Deleted</p>
                    @else
                    {!! Form::open(['route' => ['entries.destroy', $entry->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('entries.show', [$entry->id]) }}" class='btn btn-default btn'>View</a>
                        <a href="{{ route('entries.edit', [$entry->id]) }}" class='btn btn-default btn'>Edit</a>
                        {!! Form::button('Delete', ['type' => 'submit', 'class' => 'btn btn-danger btn', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                    @endif
                    --}}
                    @include('entries.views.action')
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>

@section('css')
<style>
.deleted {
    background-color: #80808030;
    -webkit-text-decoration-line: line-through;
    text-decoration-line: line-through;
}
.deleted p{
    text-decoration: none;
    display: inline-block;
}
</style>
@endsection

resources/views/frontend/timeline.blade.php
<div class="row">
        @foreach($entries as $entry)
        <div class="col-9 offset-1">
            <ul class="timeline">
                <li class="{{$entry->deleted_at!=null?'deleted':''}}">
                    <a href="#" class="float-right">{{$entry->entry_date->format('Y-m-d')}}</a>
                    <p>{{$entry->entry}}</p>
                        
                    {{--
                    @if($entry->deleted_at)
                    <label>Status :</label> 
                    <span class="{{$entry->deleted_at!=null?'span-deleted':''}}">Deleted</span>
                    @else
                    {!! Form::open(['route' => ['entries.destroy', $entry->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('entries.show', [$entry->id]) }}" class='btn btn-default btn'>View</a>
                        <a href="{{ route('entries.edit', [$entry->id]) }}" class='btn btn-default btn'>Edit</a>
                        {!! Form::button('Delete', ['type' => 'submit', 'class' => 'btn btn-danger btn', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                    @endif
                    --}}
                    @include('entries.views.action')
                </li>
            </ul> 
        </div>
        @endforeach
</div>

@section('css')
<style>
ul.timeline {
    list-style-type: none;
    position: relative;
}
ul.timeline:before {
    content: ' ';
    background: #d4d9df;
    display: inline-block;
    position: absolute;
    left: 29px;
    width: 2px;
    height: 100%;
    z-index: 400;
}
ul.timeline > li {
    margin: 20px 0;
    padding-left: 20px;
}
ul.timeline > li:before {
    content: ' ';
    background: white;
    display: inline-block;
    position: absolute;
    border-radius: 50%;
    border: 3px solid #22c0e8;
    left: 20px;
    width: 20px;
    height: 20px;
    z-index: 400;
}
.deleted{
    background-color: #80808030;
    -webkit-text-decoration-line: line-through;
    text-decoration-line: line-through;
}
.deleted .span-deleted{
    text-decoration: none;
    display: inline-block;
}
</style>
@endsection